EESSI/filesystem-layer

.github/workflows/ansible-lint.yml
README.md
group_vars/all.yml

Thought it would be useful to check/lint the playbooks that we commit. @boegel I only have limited experience with Github Action, so could you have a look at this? I left some code smells in my playbook, so that you can (hopefully) see what it does. (or not, probably only works after the PR gets accepted?)

Add Github Action for Ansible Lint 

---

stratum0.yml
stratum1.yml

Thought that the role itself would do nothing on non-Redhat distros, but @JvD007 found that it does on for instance Ubuntu. This has been fixed by adding a conditional to the playbooks.

Only run geerlingguy.repo-epel role on RedHat distros

---

README.md

Added a comment in the README to solve #15.

Note about 'become' functionality in Ansible

---

templates/eessi_localproxy_squid.conf.j2
templates/eessi_stratum1_squid.conf.j2

Fixes #19 reported by @JvD007.

Make Squid contact dual-stack websites over IPv4 first

---

README.md

The documentation points to a favorites list of videos.
From the list, I could only find this (video|https://www.youtube.com/watch?v=MyYx-xaL36k) that talks about CVMFS.
I am updating the link from the favorites list of videos to the actual video itself.

Fix CVMFS Youtube video link

---

prepare-client-packages.yml

It was using commas as separator in the list of Stratum 1 urls, this should be a semicolon.

Fix for client packages

---

.github/workflows/test-containers.yml
containers/Dockerfile.EESSI-client-pilot-centos7-aarch64
containers/Dockerfile.EESSI-client-pilot-centos7-x86_64
containers/README.md
containers/docker_build_push.sh

container images are already built with the script included here, see https://hub.docker.com/r/eessi/client-pilot/tags

update recipes for EESSI client containers for 2020.10 pilot

---

requirements.yml

Version bump of `ansible-cvmfs` (which has a nice fix/improvement for the CVMFS garbage collection) and `repo-epel`.

Version bump of Ansible roles

---

inventory/group_vars/all.yml

Closes #61. The garbage collection itself was fixed in https://github.com/galaxyproject/ansible-cvmfs/pull/31, and this is now being used via #71.

Set auto tag timespan to 30 days

---

.github/workflows/build-test-release-client-packages.yml

The `fpm` tool does add the version number to the filename of deb/rpm packages, but not to tarballs, see:
https://github.com/EESSI/filesystem-layer/releases/tag/v0.3.0
This small modification does that manually.

Add version to filenames of tarball configuration packages

---

containers/Dockerfile.EESSI-client-pilot-centos7-aarch64
containers/Dockerfile.EESSI-client-pilot-centos7-ppc64le
containers/Dockerfile.EESSI-client-pilot-centos7-x86_64

These still had the old config package installed, causing issues while the RUG Stratum 1 is down. I've pushed new versions of the images with the latest config package installed for `aarch64`, `ppc64le`, and `x86_64`; this PR contains the modified Dockerfiles.

Quick fix for Docker Hub images

---

scripts/ingest-tarball.sh

Just used this version to ingest the new compat layer tarball.
```
Using auto tag 'generic-2021-06-22T09:07:09Z'
Processing changes...
......................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................... …
```

First version of tarball ingestion script

---

containers/Dockerfile.EESSI-build-node-debian10
containers/Dockerfile.EESSI-client-pilot-centos7

Adds fuse-overlayfs to the build-node image, and switches to an older version in the client one.

Fixes for fuse-overlayfs in container images

---

.github/workflows/build-publish-containers.yml

Just noticed that the container CI didn't get run for PR #91, because it only does it when the client container Dockerfile gets changed. This should fix that, and run it for changes in any Dockerfile.

PRs that change any Dockerfile should trigger the container CI

---

.github/workflows/check-stratum-servers.yml
scripts/check-stratum-servers.py

This change prints a message if everything was okay (and which servers have been checked), and uses `tee` to print and redirect the output of the script (so that you can see it in the Github action log).

Two enhancements for stratum check script

---

.github/workflows/build-publish-containers.yml
containers/Dockerfile.EESSI-build-node-debian10

fix for:
```
/usr/bin/eessi-upload-to-staging: line 34: jq: command not found
```
should have been included in #91...

include jq in build container (required by eessi-upload-to-staging script)

---

.github/workflows/Dockerfile-ubuntu-18.04
.github/workflows/build-test-release-client-packages.yml
scripts/ingest-tarball.sh

As we've added this new `versions` directory to the root (see #32), the ingestion script should be using this in order to ingest to the right location.

Prepend ingestion base directory with "versions" directory (+ some fixes for Ansible CI workflows)

---

scripts/ingest-tarball.sh

Oops, I thought I corrected a typo in https://github.com/EESSI/filesystem-layer/pull/104, but broke the script instead... this fixes it again.

Undo change that broke the ingestion script

---

.gitignore
README.md
create_cvmfs_content_structure.yml
roles/create_cvmfs_content_structure/defaults/main.yml
roles/create_cvmfs_content_structure/files/.cvmfsdirtab
roles/create_cvmfs_content_structure/tasks/do_repo.yml
roles/create_cvmfs_content_structure/tasks/main.yml
roles/create_cvmfs_content_structure/vars/pilot.eessi-hpc.org.yml

This playbook creates the files and symlinks defined in the `vars` file of the corresponding CVMFS repo. I'm planning to set up a cronjob on the Stratum 0 that periodically does a `git pull` and runs the playbook.
Still WIP, as I want to add some README/documentation.
Closes #89. Closes #51. Closes #34.

Playbook for updating symlinks and files in the CVMFS repositories

---

.github/workflows/ansible-lint.yml
containers/Dockerfile.EESSI-build-node-debian10
containers/Dockerfile.EESSI-client-pilot-centos7
containers/build-or-download-cvmfs-debs.sh

The new version of fuse-overlayfs doesn't seem to be affected by the `Operation not permitted` issue (see https://github.com/containers/fuse-overlayfs/issues/232) anymore when used in a Singularity container. So, instead of sticking to the default (very old) version that Debian 10 provides, or building that old version manually for CentOS 7, we can now simply grab the prebuilt binary from the release page.

Use latest version of prebuilt fuse-overlayfs binary, and bump versions of CVMFS, awscli, Debian for client and build containers

---

.github/workflows/Dockerfile-rockylinux-8
.github/workflows/Dockerfile-ubuntu-18.04
.github/workflows/build-test-release-client-packages.yml
.github/workflows/test-playbooks.yml

CentOS 8 is not supported anymore, so I've replaced it by a Rocky container. The Ubuntu 18.04 container had issues with installing ansible's dependency markupsafe (see: https://github.com/pallets/markupsafe/issues/285), so I fixed that by first upgrading pip.

Fix CI issues with Ubuntu 18.04 and CentOS 8 containers, and with macOS CVMFS tests

---

roles/create_cvmfs_content_structure/tasks/do_repo.yml

The playbook used to do a `cvmfs_server publish` every time, even if no files were changed. The proposed fix here checks if something was changed, and otherwise it will abort the transaction.

Only publish CVMFS transaction if files/symlinks were changed

---

.github/workflows/ansible-lint.yml

They now use a `main` branch instead of `master`.

Fix Ansible lint action

---

roles/create_cvmfs_content_structure/tasks/do_repo.yml

The current publish transaction only triggers when symlinks and files are changed, with this edit it will publish when one of them is changed.

Change the publish transaction to trigger correctly

---

containers/Dockerfile.EESSI-build-node-debian10
containers/Dockerfile.EESSI-client-pilot-centos7
containers/build-or-download-cvmfs-debs.sh
containers/build-or-download-cvmfs-rpms.sh

See #110. Also bumped the version of CVMFS to 2.9.4.

Hide magic attributes in CVMFS configuration of EESSI containers + update to CernVM-FS 2.9.4

---

containers/Dockerfile.EESSI-build-node-debian10

If `archspec` is available in the build container directly, we have a reliable way of determining the CPU microarchitecture of a build host, without requiring that EESSI is mounted on the build host.

also install archspec in build container (+ update awscli to latest v1.x)

---

.github/workflows/build-test-release-client-packages.yml

This job is currently broken due to a silly issue (probably because we pick up an Ansible version that is too recent?
```
> Run ansible-playbook --connection=local ./prepare-client-packages.yml
ansible-playbook --connection=local ./prepare-client-packages.yml
shell: /bin/bash -e {0}
/Users/runner/work/_temp/0902b464-74fc-42e5-a721-b4a369a30dd5.sh: line 1: ansible-playbook: command not found
Error: Process completed with exit code 127.
```
Similar to #121, let's disable this for now, it shouldn't block making progress...

disable broken build-macos-package job in build-test-release-client-packages workflow

---

.github/workflows/build-publish-containers.yml
containers/Dockerfile.EESSI-build-node-debian11
containers/README.md
containers/build-or-download-cvmfs-debs.sh

This seems to fix the weird problem I was running into when installing `Qt5-5.15.2-GCCcore-10.3.0.eb` when I was using an AWS VM as a build node that is discussed in detail in https://github.com/easybuilders/easybuild-easyconfigs/issues/16614:
```
/tmp/boegel/easybuild/build/Qt5/5.15.2/GCCcore-10.3.0/qt-everywhere-src-5.15.2/qtbase/bin/qmake -install qinstall /tmp/boegel/easybuild/build/Qt5/5.15.2/GCCcore-10.3.0/qt-everywhere-src-5.15.2/qtbase/include/QtGui/QGenericPlugin /cvmfs/pilot.eessi-hpc.org/versions/2021.12/software/linux/aarch64/graviton3/software/Qt5/5.15.2-GCCcore-10.3.0/include/QtGui/QGenericPlugin
Error copying /tmp/boegel/easybuild/build/Qt5/5.15.2/GCCcore-10.3.0/qt-everywhere-src-5.15.2/qtbase/include/QtGui/QGenericPlugin to …
```

update build container to Debian 11.5 + CernVM-FS 2.10.0 + fuse-overlayfs 1.9 + awscli 1.27.8

---

containers/Dockerfile.EESSI-build-node-debian11

The main motivation for this is a bug I'm hitting when running an `emerge` command in the compat layer, which was traced down to a bug in `fuse-overlayfs`, cfr. https://bugs.gentoo.org/895144

update build container to use Debian 11.7 + fuse-overlayfs 1.12

---

containers/Dockerfile.EESSI-build-node-debian11

cfr. https://github.com/containers/fuse-overlayfs/issues/232#issuecomment-1578273859

stick to fuse-overlayfs v1.10 in build container, since v1.12 again triggers 'Operation not permitted' error for basic operations

---

.github/workflows/build-test-release-client-packages.yml

This removes the dependency on an external action, and directly calls Ansible in the runner (should already be available according to https://github.com/actions/runner-images/blob/main/images/linux/Ubuntu2204-Readme.md#tools).
Fixes #155.

Fix workflow for building client packages

---

scripts/automated_ingestion/automated_ingestion.py
scripts/automated_ingestion/eessitarball.py

Instead of calling `get_repo()` for every tarball, just call it once and pass it to the tarball objects.

Reduce the number of calls to the GitHub API

---

inventory/group_vars/all.yml
roles/cvmfs_server_meta_info/defaults/main.yml
roles/cvmfs_server_meta_info/tasks/main.yml
roles/cvmfs_server_meta_info/tasks/repo_meta_info.yml
stratum0.yml
stratum1.yml

This role updates the meta info of both the CVMFS Stratums (both 0 and 1) and the repositories (only done on Stratum 0, as this gets stored in the repo itself). See https://cvmfs.readthedocs.io/en/stable/cpt-servermeta.html. Closes #81.
For the server meta info:
```
bob@stratum0:~$ cat /srv/cvmfs/info/v1/meta.json 
{
"administrator" : "Your Name",
"email"         : "you@organisation.org",
"organisation"  : "Your Organisation",
"custom" : {
"_comment" : "Put arbitrary structured data here"
}
}
bob@stratum0:~$ cat /srv/cvmfs/info/v1/meta.json 
{
"administrator": "EESSI CVMFS Administrators",
"email": "support@eessi.io",
"organisation": "EESSI",
"custom": {
"_comment": "See https://eessi.io/docs/ for more information about the EESSI repository."
}
}
```
And for the repos:
```
bob@ssr4cc:~$ …
```

Add role for updating meta information of CVMFS servers and repositories

---

inventory/group_vars/all.yml

As we will use only one masterkey, and hence one public key, for all `eessi.io` repos, I've applied the suggestion from Dave in https://github.com/cvmfs-contrib/config-repo/pull/206/files here as well and renamed the pubkey to `eessi.io.pub`.

Rename eessi.io public key

---

.github/workflows/build-test-release-client-packages.yml

The new client package only contained the `eessi.io` configuration. By (temporarily) including the old config as well, we can ensure that people (and our build container recipes) can always grab the latest package without breaking any workflows/instructions, because they will have access to both.

Include `eessi-hpc.org` domain configuration in new EESSI CVMFS configuration

---

scripts/ingest-tarball.sh

The script will check if it's called by the user that owns the CVMFS repo, and if that's not the case it will use `sudo` for calls to `cvmfs_server`.

Use variable for `cvmfs_server` command and check if `sudo` is required

---

scripts/automated_ingestion/automated_ingestion.cfg.example
scripts/automated_ingestion/eessitarball.py

@bedroge Let's stop adding comments mentioning the PR URL...
Untested, so we need to keep an eye out after this is deployed, but should be easy to review.

mention PR url in body of staging PR

---

.github/workflows/build-publish-containers.yml

The CI that builds our Docker images failed in the last step after merging #171. This step runs `docker manifest` to create a multi-platform Docker image based on the individual images that are built for each architecture. Not sure why that doesn't work anymore, but I found an alternative that uses `docker buildx imagetools`. Also see:
https://docs.docker.com/engine/reference/commandline/buildx_imagetools_create/
https://stackoverflow.com/a/75742743
https://github.com/docker/buildx/issues/1509
Tested this in a test repo:
https://github.com/bedroge/dockertest
https://github.com/bedroge/dockertest/pkgs/container/client

Fix issue with creating multi-platform Docker images

---

containers/Dockerfile.EESSI-build-node-debian11

Just making a small change here to trigger the updated CI (see #173) and rebuild our container images, as it failed after merging #171.

Bump `awscli` to 1.32.22 in build container

---

scripts/ingest-tarball.sh

When ingesting an updated compat layer, this adds a suffix to the existing one instead of removing them.
Example / test on the pilot repo with only `/cvmfs/pilot.eessi-hpc.org/versions/2023.06/compat/linux/x86_64` in place:
```
Compatibility layer for version 2023.06, OS linux, and architecture x86_64 already exists!
Moving the existing compat layer to /cvmfs/pilot.eessi-hpc.org/versions/2023.06/compat/linux/x86_64-001...
```
Doing it once more with both `/cvmfs/pilot.eessi-hpc.org/versions/2023.06/compat/linux/x86_64` and `/cvmfs/pilot.eessi-hpc.org/versions/2023.06/compat/linux/x86_64-001` already in place:
```
Compatibility layer for version 2023.06, OS linux, and architecture x86_64 already exists!
Moving the existing compat layer from …
```

Let ingestion script move existing compat layers instead of removing them

---

.github/workflows/build-test-release-client-packages.yml

This should solve the failing CI (see #177) for building our packages:
```
#11 [6/7] RUN gem install --no-document fpm -v 1.11.0
#11 48.39 ERROR:  Error installing fpm:
#11 48.39 	The last version of dotenv (>= 0) to support your Ruby & RubyGems was 2.8.1. Try installing it with `gem install dotenv -v 2.8.1` and then running the current command again
#11 48.39 	dotenv requires Ruby version >= 3.0. The current ruby version is 2.7.8.225.
#11 48.64 Successfully installed stud-0.0.23
#11 ERROR: process "/bin/sh -c gem install --no-document fpm -v 1.11.0" did not complete successfully: exit code: 1
```

Bump FPM action to latest commit

---

inventory/group_vars/all.yml

This allows anyone to set up a private Stratum 1 using the `stratum1.yml` playbook.

Use EESSI sync server as Stratum 0

---

scripts/ingest-tarball.sh
scripts/update_lmod_caches.sh

Closes https://github.com/EESSI/software-layer/issues/167. Could perhaps be made a bit smarter by only updating the cache of the subtree that's being modified. But that's a bit more effort (can be taken from the filename of the tarball), and may not work anymore if we want to combine all tarballs into a single one.

Add script for updating Lmod caches

---

.gitignore
README.md
client.yml
localproxy.yml
requirements.yml
stratum0.yml
stratum1.yml
templates/eessi_stratum1_squid.conf.j2

I've forked https://github.com/galaxyproject/ansible-cvmfs to https://github.com/EESSI/ansible-cvmfs, and made some changes that we really need for S3 support and key directories. This PR changes the playbooks, README, and requirements file to use our fork.

Use our fork of the `ansible-cvmfs` role

---

scripts/automated_ingestion/eessitarball.py

Tested this with `eessi-2023.06-software-linux-aarch64-a64fx-1719346462.tar.gz`, with these changes I get the following as `members_list` (as expected):
```
['2023.06/init/easybuild/eb_hooks.py',
'2023.06/software/linux/aarch64/a64fx/modules/all/BLIS/0.9.0-GCC-12.3.0.lua',
'2023.06/software/linux/aarch64/a64fx/modules/all/CMake/3.26.3-GCCcore-12.3.0.lua',
'2023.06/software/linux/aarch64/a64fx/modules/all/FFTW.MPI/3.3.10-gompi-2023a.lua',
'2023.06/software/linux/aarch64/a64fx/modules/all/FFTW/3.3.10-GCC-12.3.0.lua',
'2023.06/software/linux/aarch64/a64fx/modules/all/FlexiBLAS/3.3.1-GCC-12.3.0.lua',
'2023.06/software/linux/aarch64/a64fx/modules/all/OpenBLAS/0.3.23-GCC-12.3.0.lua',
'2023.06/software/linux/aarch64/a64fx/modules/all/Python/3.11.3-GCCcore-12.3.0.lua', …
```

try to determine common prefix for paths in tarball after filtering out `*/init/*` paths

---

requirements.yml

Let's see if this fixes the broken CI (https://github.com/EESSI/filesystem-layer/actions/runs/9676886245) by using the change from https://github.com/EESSI/ansible-cvmfs/pull/13.

Use latest commit of eessi.cvmfs

---

scripts/update_lmod_caches.sh

Running it on the Stratum 0 in an open (but aborted) transaction shows the following for zen2 and zen3 (the only CPU targets for which we have accelerator modules at the moment):
```
Updated the Lmod cache for /cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/amd/zen2 using MODULEPATH: /cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/amd/zen2/accel/nvidia/cc80/modules/all:/cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/amd/zen2/modules/all.
Updated the Lmod cache for /cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/amd/zen3 using MODULEPATH: /cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/amd/zen3/accel/nvidia/cc80/modules/all:/cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/amd/zen3/modules/all. …
```

Include accelerator modules in Lmod caches

---

scripts/automated_ingestion/automated_ingestion.cfg.example
scripts/automated_ingestion/automated_ingestion.py
scripts/automated_ingestion/eessitarball.py
scripts/ingest-tarball.sh
scripts/test-ingest-tarball.sh

This allows you to specify a dictionary of buckets in the configuration, and map them to CVMFS repositories, e.g.:
```
staging_buckets = {
"software.eessi.io-2023.06": "software.eessi.io",
"dev.eessi.io-2024.09": "dev.eessi.io",
"riscv.eessi.io-20240402": "riscv.eessi.io" }
```
The ingestion script has been adjusted as well: you now have to specify to which repo a tarball has to be ingested. The tests for this script have been adjusted accordingly:
```
$ ./test-ingest-tarball.sh 
Ran 31 tests, 31 succeeded, 0 failed.
```
Finally, the automated ingestion now also prints the target CVMFS repo in the PR title+description, and in the Slack message.

[Automated ingestion] Map S3 buckets to CVMFS repositories

---

containers/Dockerfile.EESSI-client-rocky8
containers/build-or-download-cvmfs-debs.sh
containers/build-or-download-cvmfs-rpms.sh

With this included, a user could:
- Start the EESSI container on a new target system
- Load the environment they want to export (source EESSI, load their required modules)
- Run a script (yet to be created) that would
- Generate a spec file for `cvmfs_shrinkwrap` based on the current environment
- Run `cvmfs_shrinkwrap` to export the environment
- Run `mksquashfs` to create a squashfs from the export
- Tidy up
The resulting squashfs could be loaded in _any_ container (with Linux and a supported shell). One could give a hint about how to enable `host_injections` with the export.

Add cvmfs_shrinkwrap to EESSI container to enable exporting EESSI environment

---

scripts/automated_ingestion/eessitarball.py

This is a workaround for https://github.com/PyGithub/PyGithub/issues/3179.

Fix for automated ingestion due to a change in the Github API for non-existing files

---

.github/workflows/build-test-release-client-packages.yml
scripts/automated_ingestion/automated_ingestion.cfg.example
scripts/automated_ingestion/eessitarball.py

Still testing it, but first tests look good. I'm running a separate instance/fork of the automated ingestion on the Stratum 0, configured to use a test bucket and non-existing target repo. This successfully picked up the tarball+metadata file and their signatures from the test bucket (uploaded by @trz42  in https://github.com/EESSI/software-layer/pull/968):
```
-rw-r--r--. 1 eessi eessi 124619768 Mar 20 16:12 eessi-2023.06-software-linux-aarch64-nvidia-grace-1741954310.tar.gz
-rw-r--r--. 1 eessi eessi       663 Mar 20 16:12 eessi-2023.06-software-linux-aarch64-nvidia-grace-1741954310.tar.gz.meta.txt
-rw-r--r--. 1 eessi eessi       878 Mar 20 16:12 eessi-2023.06-software-linux-aarch64-nvidia-grace-1741954310.tar.gz.meta.txt.sig
-rw-r--r--. 1 eessi eessi       878 Mar 20 16:12 …
```

Add functionality for verifying tarball signatures to automated ingestion scripts

---

scripts/ingest-tarball.sh
scripts/test-ingest-tarball.sh

We're not checking the exit code after doing the Lmod cache update, we should.
Trigger for this is missing Lmod cache files currently for `intel/cascadelake` and `intel/icelake` CPU targets:
```
$ ls -lrtd /cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/intel/*/.lmod/cache
drwxr-xr-x 2 cvmfs cvmfs 117 May 28 23:36 /cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/intel/haswell/.lmod/cache
drwxr-xr-x 2 cvmfs cvmfs 117 May 28 23:36 /cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/intel/skylake_avx512/.lmod/cache
drwxr-xr-x 2 cvmfs cvmfs 117 May 28 23:36 /cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/intel/sapphirerapids/.lmod/cache
```
Note: this is totally untested!

abort transaction if Lmod cache update failed

---

.github/workflows/test-containers.yml
containers/Dockerfile.EESSI-build-node-debian11

Latest version of `bwrap` (0.11.0) includes support for creating writable overlays, so perhaps we can move away from the dreaded `fuse-overlayfs` and use `bwrap` instead?
I would like to add `bwrap` to our build container, so I can experiment with this...

build and install `bwrap` from source in Debian 11 build container

---

containers/Dockerfile.EESSI-build-node-debian12

Seems like I found an alternative to `fuse-overlayfs` which doesn't suffer from the problems we see with it for rebuilds.
Using:
```
apptainer shell --contain ... --fusemount "container:unionfs -o cow -o relaxed_permissions /tmp/$USER/software.eessi.io=RW:/cvmfs_ro/software.eessi.io=RO /cvmfs/software.eessi.io" docker://ghcr.io/boegel/build-node:debian12-amd64
```
(rather than the equivalent using `fuse-overlayfs`), I obtained an environment in which I could happily remove directories like `/cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/intel/cascadelake/software/EESSI-extend/2023.06-easybuild`

build and install recent `unionfs-fuse` version (replacing `fuse-overlayfs`) in Debian 12 build container

---

scripts/automated_ingestion/eessitarball.py

It will just include the three levels deep directory names (and not their contents) under `reprod`, e.g.:
```
2025.06/software/linux/x86_64/intel/skylake_avx512/reprod/EasyBuild/5.1.1/20250718_190714UTC
```

Print directory names of reprod subdirs in staging PR's tarball overview
